### ISSUE TITLE
Can you support more data formats？

### ISSUE THREAD

**Issue by Lu-Li-github** [Jie-Cheng/lab-data-converter#1]
Can you support more data formats?
For example, the txt file...

**Comment by Jie-Cheng** [comment]
txt is not a data format. It is just a file extension. I need more description on the "txt file".

**Comment by Lu-Li-github** [comment]
Please see attached file.

The first column is X, the second column is Y.

[TXT sample.txt](https://github.com/Jie-Cheng/lab-data-converter/files/3753439/TXT.sample.txt)
